/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ZustandIndexImport } from './routes/Zustand/index'
import { Route as XstateIndexImport } from './routes/Xstate/index'
import { Route as ValtioIndexImport } from './routes/Valtio/index'
import { Route as ReduxToolkitIndexImport } from './routes/ReduxToolkit/index'
import { Route as RecoilIndexImport } from './routes/Recoil/index'
import { Route as MobXIndexImport } from './routes/MobX/index'
import { Route as JotaiIndexImport } from './routes/Jotai/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ZustandIndexRoute = ZustandIndexImport.update({
  path: '/Zustand/',
  getParentRoute: () => rootRoute,
} as any)

const XstateIndexRoute = XstateIndexImport.update({
  path: '/Xstate/',
  getParentRoute: () => rootRoute,
} as any)

const ValtioIndexRoute = ValtioIndexImport.update({
  path: '/Valtio/',
  getParentRoute: () => rootRoute,
} as any)

const ReduxToolkitIndexRoute = ReduxToolkitIndexImport.update({
  path: '/ReduxToolkit/',
  getParentRoute: () => rootRoute,
} as any)

const RecoilIndexRoute = RecoilIndexImport.update({
  path: '/Recoil/',
  getParentRoute: () => rootRoute,
} as any)

const MobXIndexRoute = MobXIndexImport.update({
  path: '/MobX/',
  getParentRoute: () => rootRoute,
} as any)

const JotaiIndexRoute = JotaiIndexImport.update({
  path: '/Jotai/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Jotai/': {
      preLoaderRoute: typeof JotaiIndexImport
      parentRoute: typeof rootRoute
    }
    '/MobX/': {
      preLoaderRoute: typeof MobXIndexImport
      parentRoute: typeof rootRoute
    }
    '/Recoil/': {
      preLoaderRoute: typeof RecoilIndexImport
      parentRoute: typeof rootRoute
    }
    '/ReduxToolkit/': {
      preLoaderRoute: typeof ReduxToolkitIndexImport
      parentRoute: typeof rootRoute
    }
    '/Valtio/': {
      preLoaderRoute: typeof ValtioIndexImport
      parentRoute: typeof rootRoute
    }
    '/Xstate/': {
      preLoaderRoute: typeof XstateIndexImport
      parentRoute: typeof rootRoute
    }
    '/Zustand/': {
      preLoaderRoute: typeof ZustandIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  JotaiIndexRoute,
  MobXIndexRoute,
  RecoilIndexRoute,
  ReduxToolkitIndexRoute,
  ValtioIndexRoute,
  XstateIndexRoute,
  ZustandIndexRoute,
])

/* prettier-ignore-end */
